version: '3'
services:

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    networks:
      - my_network
    volumes:
      - db2:/data/db
  
  memcached:
    image: bitnami/memcached:latest
    volumes:
      - db2:/data/db 
    networks:
      - my_network 
    ports:
      - "11211:11211" 
  
  reviews:
    build:
      context: .
      dockerfile: reviews/Dockerfile-reviews
    networks:
      - my_network
    depends_on:
      - mongodb
      - memcached
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    extra_hosts:
      - "mongoservice:172.17.0.1"
    environment:
      - HOSTNAME=mongodb
      - USE_REVERSE_PROXY=false
      - USE_ELASTICSEARCH=false

    

networks:
  my_network:

volumes:
  db2: