version: '3'
services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./media:/media
    networks:
      - my_network
    labels:
      - "traefik.http.routers.media.rule=PathPrefix(`/media/`)"
      - "traefik.http.services.media.loadbalancer.server.port=80"
      - "traefik.http.services.media.loadbalancer.server.path=/media"

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    networks:
      - my_network
    volumes:
      - db2:/data/db
  
  reviews:
    build:
      context: .
      dockerfile: reviews/Dockerfile-reviews
    networks:
      - my_network
    depends_on:
      mongodb:
        condition: service_started
      traefik:
        condition: service_started
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    extra_hosts:
      - "mongoservice:172.17.0.1"
    environment:
      - HOSTNAME=mongodb
      - USE_REVERSE_PROXY=true
      - USE_ELASTICSEARCH=false
    labels:
      - "traefik.http.routers.reviews.rule=Host(`app.localhost`)"
      - "traefik.http.services.reviews.loadbalancer.server.port=8000" 

networks:
  my_network:

volumes:
  db2:
