version: '3'
services:

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    networks:
      - my_network
    volumes:
      - db:/data/db

  reviews:
    build:
      context: .
      dockerfile: reviews/Dockerfile-reviews
    networks:
      - my_network
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    environment:
      - DOCKER_CONTAINER=true
    extra_hosts:
      - "mongoservice:172.17.0.1"

networks:
  my_network:

volumes:
  db:
