# Generated by Django 4.1.13 on 2024-08-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="myapp.book"
            ),
        ),
    ]
